Server:
  # dev 开发模式 prod 生产模式
  AppMode: dev
  Host: localhost
  Port: 8080
  # Jwt加密秘钥
  JwtKey: xxxxx
  # Jwt 过期时间，单位为 minutes
  JwtExpireTime: 10
  # 图片验证码过期时间，单位为 minutes
  CaptchaExpireTime: 10
  # 图片验证码 MD5 哈希前缀
  CaptchaKey: yyyy
  Database:
    Type: mysql
    Host: localhost
    Port: 3307
    User: root
    PassWord: 123456
    Name: code_sandbox_data
    Redis:
      Host: localhost
      Port: 6379
      Password:
      Db: 0
  Oss:
    #oss服务商，支持[qiniu,aliyun]
    Name: aliyun
    qiniu:
      AccessKey:
      SecretKey:
      Bucket:
      Sever:
    aliyun:
      AccessKeyId:
      AccessKeySecret:
      Endpoint:
      BucketName:

  Email:
    # 发送方和授权码
    From: notification@yalexin.top
    Password:
    # 抄送地址
    To: me@yalexin.top
    Host: smtp.exmail.qq.com
    Port: 465
  Rate:
    # 在 GlobalTime 之内允许请求不超过 GlobalCount 次
    GlobalCount: 20
    # 单位为秒
    GlobalTime: 1
    LoginCount: 1
    LoginTime: 1
    RegisterCount: 1
    RegisterTime: 60
    ExecuteCodeCount: 1
    ExecuteCodeTime: 10
    ProgramExecuteCodeCount: 1
    ProgramExecuteCodeTime: 2
SandboxMachine:
  Host: 192.168.254.148
  Port: 2375
DockerInfoList:
  - Language: Go-1.17
    ImageName: golang:1.17
    ContainerCount: 3
    Filename: Main.go
    CompileCmd: "go build Main.go"
    RunCmd: "./Main"
  - Language: Java-8
    ImageName: openjdk:8-alpine
    ContainerCount: 2
    Filename: Main.java
    CompileCmd: "javac Main.java -encoding utf-8"
    RunCmd: "java Main"
  - Language: C
    ImageName: gcc:6.3.0
    ContainerCount: 2
    Filename: Main.c
    CompileCmd: "gcc Main.c -o Main"
    RunCmd: "./Main"
  - Language: Python-3.9
    ImageName: python:3.9
    ContainerCount: 2
    Filename: Main.py
    CompileCmd: "echo python"
    RunCmd: "python Main.py"
