definitions:
  dto.ExecuteCodeRequest:
    description: 用户需要提交的代码执行请求参数
    properties:
      code:
        type: string
      inputList:
        description: 运行用例组，每一个元素代表一个用例，例如 1 2\n
        items:
          type: string
        type: array
      language:
        type: string
    type: object
  dto.UserLoginRequest:
    description: 用户注册请求参数
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  dto.UserRegisterRequest:
    description: 用户注册请求参数
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  responses.Response:
    properties:
      code:
        description: 错误码
        type: integer
      data:
        description: 返回数据
      msg:
        description: 错误描述
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/executeCode:
    post:
      consumes:
      - application/json
      description: 根据用户提交的代码和语言执行代码并返回结果
      parameters:
      - description: 执行代码请求
        in: body
        name: executeCodeRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ExecuteCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 执行代码
      tags:
      - Code Execution
  /api/v1/languages:
    get:
      consumes:
      - application/json
      description: 获取支持的语言列表，只有在该列表中的语言代码才能运行
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 获取支持的语言列表
      tags:
      - Languages
  /api/v1/user/keys:
    get:
      consumes:
      - application/json
      description: 展示用户的密钥对
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 展示用户的密钥对
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 提交用户名和密码
      parameters:
      - description: 登录表单
        in: body
        name: userLoginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 用户登录
  /api/v1/user/newKey:
    post:
      consumes:
      - application/json
      description: 生成密钥对，用于通过程序式提交代码
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 生成密钥对
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 提交用户名，邮箱和密码
      parameters:
      - description: 用户信息
        in: body
        name: userRegisterRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 用户注册
swagger: "2.0"
