definitions:
  dto.ChangePasswordRequest:
    properties:
      newPassword:
        description: 新密码
        type: string
      oldPassword:
        description: 旧密码
        type: string
    type: object
  dto.DeleteKeyRequest:
    properties:
      id:
        description: 要删除的密钥 id
        type: integer
    type: object
  dto.ExecuteCodeRequest:
    description: 用户需要提交的代码执行请求参数
    properties:
      code:
        type: string
      inputList:
        description: 运行用例组，每一个元素代表一个用例，例如 1 2\n
        items:
          type: string
        type: array
      language:
        type: string
    type: object
  dto.ExecuteCodeResponse:
    properties:
      executeMessages:
        items:
          $ref: '#/definitions/vo.ExecuteMessageVO'
        type: array
    type: object
  dto.PageExecutionRequest:
    description: 执行记录请求参数
    properties:
      pageNum:
        description: 页码数
        type: integer
      pageSize:
        description: 每页大小
        type: integer
    type: object
  dto.UserLoginRequest:
    description: 用户注册请求参数
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  dto.UserRegisterRequest:
    description: 用户注册请求参数
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  responses.Response:
    properties:
      code:
        description: 错误码
        type: integer
      data:
        description: 返回数据
      msg:
        description: 错误描述
        type: string
    type: object
  vo.CaptchaVO:
    properties:
      imageBase64:
        description: 验证码 base64
        type: string
      token:
        description: 登录和注册要带上
        type: string
    type: object
  vo.ExecuteMessageVO:
    properties:
      errorMessage:
        description: 脱敏信息，将 docker 容器的错误信息做进一步处理
        type: string
      exitCode:
        type: integer
      memoryCost:
        type: integer
      message:
        type: string
      timeCost:
        type: integer
    type: object
  vo.ExecutionVO:
    properties:
      code:
        description: 代码
        type: string
      createAt:
        description: 代码执行时间戳
        type: string
      id:
        description: id
        type: integer
      inputList:
        description: 所有的输入用例
        items:
          type: string
        type: array
      keyPairId:
        description: 使用的密钥对ID
        type: integer
      language:
        description: 编程语言
        type: string
      maxMemoryCost:
        description: 单个输入用例的最大内存消耗
        type: integer
      maxTimeCost:
        description: 单个输入用例的最大时间消耗
        type: integer
      outputList:
        description: 所有的输入用例
        items:
          type: string
        type: array
      status:
        description: 执行状态
        type: integer
    type: object
  vo.KeyPairVO:
    properties:
      accessKey:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      secretKey:
        type: string
      userId:
        type: integer
    type: object
  vo.PageDataVO:
    properties:
      data:
        description: 实际数据
      pageCount:
        description: 页码数量
        type: integer
      total:
        description: 总数据数目
        type: integer
    type: object
  vo.UserDetailVO:
    properties:
      createAt:
        description: 注册时间
        type: string
      currentUsage:
        description: 每月已用额度
        type: integer
      email:
        description: 邮箱
        type: string
      id:
        type: integer
      monthLimit:
        description: 每月限额
        type: integer
      role:
        description: 权限 0管理员 1 普通用户
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  vo.UserVO:
    properties:
      id:
        type: integer
      role:
        description: '权限 1:管理员 10: 普通用户'
        type: integer
      token:
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/captcha:
    get:
      consumes:
      - application/json
      description: 生成验证码，需要用验证码的地方有登录和注册
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.CaptchaVO'
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 生成验证码
      tags:
      - Captcha
  /api/v1/executeCode:
    post:
      consumes:
      - application/json
      description: 根据用户提交的代码和语言执行代码并返回结果
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      - description: 执行代码请求
        in: body
        name: executeCodeRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ExecuteCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/dto.ExecuteCodeResponse'
                  - properties:
                      executeMessages:
                        items:
                          $ref: '#/definitions/vo.ExecuteMessageVO'
                        type: array
                    type: object
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 执行代码
      tags:
      - Code Execution
  /api/v1/languages:
    get:
      consumes:
      - application/json
      description: 获取支持的语言列表，只有在该列表中的语言代码才能运行
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 获取支持的语言列表
      tags:
      - Languages
  /api/v1/user/changePwd:
    put:
      consumes:
      - application/json
      description: 修改密码
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      - description: 修改密码表单
        in: body
        name: changePasswordRequest
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  type: integer
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 修改密码
      tags:
      - ChangePassword
  /api/v1/user/delKey:
    delete:
      consumes:
      - application/json
      description: 删除指定 id 的密钥对
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      - description: 删除表单
        in: body
        name: deleteKeyRequest
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  type: integer
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 删除指定 id 的密钥对
      tags:
      - DeleteKey
  /api/v1/user/execution:
    post:
      consumes:
      - application/json
      description: 获取用户的代码执行记录
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      - description: 分页信息
        in: body
        name: pageExecutionRequest
        required: true
        schema:
          $ref: '#/definitions/dto.PageExecutionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  items:
                    allOf:
                    - $ref: '#/definitions/vo.PageDataVO'
                    - properties:
                        data:
                          items:
                            $ref: '#/definitions/vo.ExecutionVO'
                          type: array
                      type: object
                  type: array
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 获取用户的代码执行记录
      tags:
      - PageExecution
  /api/v1/user/info:
    get:
      consumes:
      - application/json
      description: 展示用户的信息
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/vo.UserDetailVO'
                  type: array
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 展示用户的信息
      tags:
      - UserInfo
  /api/v1/user/keys:
    get:
      consumes:
      - application/json
      description: 展示用户的密钥对
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/vo.KeyPairVO'
                  type: array
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 展示用户的密钥对
      tags:
      - KeyList
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 提交用户名和密码
      parameters:
      - description: 登录表单
        in: body
        name: userLoginRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginRequest'
      - description: 验证码凭证，获取”验证码“接口后会返回该凭证
        in: header
        name: CPT-Token
        required: true
        type: string
      - description: 验证码,对应于图片中的内容
        in: query
        name: captcha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.UserVO'
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 用户登录
      tags:
      - Login
  /api/v1/user/newKey:
    post:
      consumes:
      - application/json
      description: 生成密钥对，用于通过程序式提交代码
      parameters:
      - description: 登录凭证，登录成功后会返回该凭证
        in: header
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/responses.Response'
            - properties:
                data:
                  $ref: '#/definitions/vo.KeyPairVO'
              type: object
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 生成密钥对
      tags:
      - NewKey
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 提交用户名，邮箱和密码
      parameters:
      - description: 验证码凭证，获取”验证码“接口后会返回该凭证
        in: header
        name: CPT-Token
        required: true
        type: string
      - description: 用户信息
        in: body
        name: userRegisterRequest
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegisterRequest'
      - description: 验证码,对应于图片中的内容
        in: query
        name: captcha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            $ref: '#/definitions/responses.Response'
        "400":
          description: 错误响应
          schema:
            $ref: '#/definitions/responses.Response'
        "500":
          description: 系统内部错误
          schema:
            $ref: '#/definitions/responses.Response'
      summary: 用户注册
      tags:
      - Register
swagger: "2.0"
