package global

const (
	SUCCESS                     = 0     // "OK",
	PARAMS_ERROR                = 40000 // "请求参数错误",
	DATA_REPEAT_ERROR           = 40001 // "数据重复",
	USET_REPEAT_ERROR           = 40002 // "用户重复",
	TOO_MANY_INPUT_ERROR        = 40003 // "输入用例过多",
	PWD_FORMAT_ERROR            = 40004 // "密码格式错误，同时包含小写字母、大小字母和数字，8~16位",
	EMAIL_FORMAT_ERROR          = 40005 // "邮箱格式错误",
	LANGUAGE_NOT_SURPPORT_ERROR = 40006 // "不支持的编程语言",
	REPEAT_CHECK_ERROR          = 40007 // "已激活，请勿重复",
	NOT_LOGIN_ERROR             = 40100 // "未登录",
	NO_AUTH_ERROR               = 40101 // "无权限",
	LACK_AUTH_ERROR             = 40102 // "权限不足",
	BAN_ERROR                   = 40103 // "已经禁用该用户",
	TOKEN_WRONG_ERROR           = 40104 // "Token错误",
	TOKEN_RUNTIME_ERROR         = 40105 // "Token过期",
	TOKEN_NOT_FOUND_ERROR       = 40106 // "Header 缺少 Token",
	CPT_TOKEN_NOT_FOUND_ERROR   = 40107 // "Header 缺少 CPT-Token",
	CAPTCHA_NOT_FOUND_ERROR     = 40108 // "参数缺少 captcha",
	NOT_AUDIT_ERROR             = 40109 // "未审核该用户",
	NOT_FOUND_ERROR             = 40400 // "请求数据不存在",
	NOT_FOUND_USER_ERROR        = 40401 // "用户不存在",
	PWD_ERROR                   = 40402 // "密码错误",
	INSUFF_AMOUNT_ERROR         = 40403 // "调用额度不足",
	USER_TRY_TIME_EXPIRE        = 40404 // "体验时间已过",
	FORBIDDEN_ERROR             = 40300 // "禁止访问",
	TOO_MANY_REQUESTS_ERROR     = 42900 // "请求过快",
	TOO_KEY_ERROR               = 42901 // "key个数超限",
	SYSTEM_ERROR                = 50000 // "系统内部异常",
	OPERATION_ERROR             = 50001 // "操作失败",
	KEY_PAIR_ERROR              = 50002 // "密钥错误",
	CAPTCHA_WRONG_ERROR         = 50003 // "验证码错误",
	API_REQUEST_ERROR           = 50020 // "外部API调用失败",
	MAINTAIN_ERROR              = 50100 // "系统维护期，该功能暂不可用",
)

var codemsg = map[int]string{
	SUCCESS:                     "OK",
	PARAMS_ERROR:                "请求参数错误",
	DATA_REPEAT_ERROR:           "数据重复",
	TOO_MANY_INPUT_ERROR:        "输入用例过多",
	PWD_FORMAT_ERROR:            "密码格式错误，同时包含小写字母、大小字母和数字，8~16位",
	EMAIL_FORMAT_ERROR:          "邮箱格式错误",
	LANGUAGE_NOT_SURPPORT_ERROR: "不支持的编程语言",
	REPEAT_CHECK_ERROR:          "已激活，请勿重复",
	USET_REPEAT_ERROR:           "用户重复",
	NOT_LOGIN_ERROR:             "未登录",
	NO_AUTH_ERROR:               "无权限",
	LACK_AUTH_ERROR:             "权限不足",
	BAN_ERROR:                   "已经禁用该用户",
	TOKEN_WRONG_ERROR:           "Token错误",
	TOKEN_RUNTIME_ERROR:         "Token过期",
	TOKEN_NOT_FOUND_ERROR:       "Header 缺少 Token",
	CPT_TOKEN_NOT_FOUND_ERROR:   "Header 缺少 CPT-Token",
	CAPTCHA_NOT_FOUND_ERROR:     "参数缺少 captcha",
	NOT_AUDIT_ERROR:             "未审核该用户",
	NOT_FOUND_ERROR:             "请求数据不存在",
	NOT_FOUND_USER_ERROR:        "用户不存在",
	PWD_ERROR:                   "密码错误",
	INSUFF_AMOUNT_ERROR:         "调用额度不足",
	USER_TRY_TIME_EXPIRE:        "体验时间已过",
	FORBIDDEN_ERROR:             "禁止访问",
	TOO_KEY_ERROR:               "key个数超限",
	TOO_MANY_REQUESTS_ERROR:     "请求过快",
	SYSTEM_ERROR:                "系统内部异常",
	OPERATION_ERROR:             "操作失败",
	KEY_PAIR_ERROR:              "密钥错误",
	CAPTCHA_WRONG_ERROR:         "验证码错误",
	API_REQUEST_ERROR:           "外部API调用失败",
	MAINTAIN_ERROR:              "系统维护期，该功能暂不可用",
}

func GetErrMsg(code int) string {
	return codemsg[code]
}
